.test:
  before_script:
  - git submodule update --init --recursive
  - apt-get update
  - apt-get install -qy default-jdk-headless
  - pip install tox
  artifacts:
    paths:
      - htmlcov
    expire_in: 1 week

lint:
  image: python:3.7
  before_script:
    - pip install tox
  script: tox -e lint

py37:
  extends: .test
  image: python:3.7
  script: tox -e py37

py38:
  extends: .test
  image: python:3.8-rc
  script: tox -e py38

doc:
  extends: .test
  image: python:3.7
  script: tox -e doc
  artifacts:
    paths:
      - docs/_build/html
    expire_in: 1 week
