.lint:
  before_script:
    - pip install gitlint pre-commit tox
  script:
    - gitlint
    - pre-commit run --all-files
    - tox -e lint

.test:
  before_script:
    - git submodule update --init --recursive
    - apt-get update
    - apt-get install -qy default-jdk-headless
    - pip install tox
  artifacts:
    paths:
      - htmlcov
    expire_in: 1 week

lint37:
  extends: .lint
  image: python:3.7

lint38:
  extends: .lint
  image: python:3.8

py37:
  extends: .test
  image: python:3.7
  script: tox -e py37

py38:
  extends: .test
  image: python:3.8
  script: tox -e py38

doc:
  extends: .test
  image: python:3.8
  script: tox -e doc
  artifacts:
    paths:
      - docs/_build/html
    expire_in: 1 week

readme_dev:
# Test the code in "Development" in README.rst.
  image: python:latest
  before_script:
    - apt-get update
    - apt-get install -qy default-jdk-headless
    - pip install poetry
  script:
    - poetry install
    - poetry run pre-commit install
    - poetry run pre-commit install --hook-type commit-msg
    - git submodule update --init
    - poetry run invoke build
    - poetry run invoke fmt
    - poetry run invoke lint
    - poetry run invoke test
#   - poetry run invoke bench
    - poetry run invoke doc
    - poetry run invoke build-sdist
