repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        language_version: python3
-   repo: https://github.com/timothycrosley/isort
    rev: 5.7.0
    hooks:
    -   id: isort
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        language_version: python3
        additional_dependencies:
        -   flake8-bandit==2.1.2
        -   flake8-bugbear==20.11.1
        -   flake8-builtins==1.5.3
        -   flake8-comprehensions==3.3.1
        -   flake8-docstrings==1.5.0
        -   flake8-pytest-style==1.3.0
        -   pep8-naming==0.11.1
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
    -   id: mypy
        language_version: python3
        additional_dependencies:
        -   jpype1==1.1.2
        -   py4j==0.10.9.1
        -   pyjnius==1.3.0
        args:
        -   --ignore-missing-imports
        -   --no-pretty
        -   --scripts-are-modules
-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.15.0
    hooks:
    -   id: gitlint
