default_install_hook_types: [pre-commit, commit-msg]

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: destroyed-symlinks
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: mixed-line-ending
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
    -   id: black

-   repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
    -   id: isort

-   repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.7.3
    hooks:
    -   id: editorconfig-checker

-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        additional_dependencies:
        -   flake8-bandit==4.1.1
        -   flake8-bugbear==24.2.6
        -   flake8-builtins==2.2.0
        -   flake8-comprehensions==3.14.0
        -   flake8-docstrings==1.7.0
        -   Flake8-pyproject==1.2.3
        -   flake8-pytest-style==1.7.2
        -   pep8-naming==0.13.3

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy
        args: []
        additional_dependencies:
        -   invoke==2.2.0
        -   jpype1==1.5.0
        -   py4j==0.10.9.7
        -   pyjnius==1.6.1
        -   pytest==7.4.4
        -   types-setuptools==69.0.0.20240125

-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
    -   id: shellcheck
        args: [-x]

-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.18.0  # https://github.com/jorisroovers/gitlint/issues/535
    hooks:
    -   id: gitlint
