repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.3.54
    hooks:
    -   id: editorconfig-checker
-   repo: https://github.com/psf/black
    rev: 21.11b1
    hooks:
    -   id: black
        language_version: python3
-   repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
    -   id: isort
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        language_version: python3
        additional_dependencies:
        -   flake8-bandit==2.1.2
        -   flake8-bugbear==21.9.2
        -   flake8-builtins==1.5.3
        -   flake8-comprehensions==3.7.0
        -   flake8-docstrings==1.6.0
        -   flake8-pytest-style==1.5.1
        -   pep8-naming==0.12.1
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
    -   id: mypy
        language_version: python3
        additional_dependencies:
        -   jpype1==1.3.0
        -   py4j==0.10.9.2
        -   pyjnius==1.4.1
        -   types-setuptools==57.4.2
        args:
        -   --ignore-missing-imports
        -   --no-pretty
        -   --scripts-are-modules
-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.16.0
    hooks:
    -   id: gitlint
