name: CI

on: [push, pull_request]

jobs:
  lint:
    strategy:
      matrix:
        python: [ 3.7, 3.8, 3.9 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        uses: actions/checkout@v2
        with:
          # See: https://github.com/actions/checkout/issues/116#issuecomment-569367620
          token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          repository: tueda/donuts
          path: donuts/java/donuts-java
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: pip install gitlint pre-commit tox
      - run: gitlint
      - run: pre-commit run --all-files
      - run: tox -e lint
  build:
    strategy:
      matrix:
        python: [ 3.7, 3.8, 3.9 ]
        java: [ 8, 11 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        uses: actions/checkout@v2
        with:
          # See: https://github.com/actions/checkout/issues/116#issuecomment-569367620
          token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          repository: tueda/donuts
          path: donuts/java/donuts-java
      - name: Update submodules
        run: git submodule update
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Install dependencies
        run: pip install tox tox-gh-actions
      - run: tox
      - name: Run tox (py4j)
        env:
          DONUTS_PYTHON_BACKEND: py4j
        run: tox
  readme_dev:
    # Test the code in "Development" in README.rst.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        uses: actions/checkout@v2
        with:
          # See: https://github.com/actions/checkout/issues/116#issuecomment-569367620
          token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          repository: tueda/donuts
          path: donuts/java/donuts-java
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install dependencies
        run: pip install poetry
      - name: Test the development section
        run: |
          poetry install
          poetry run pre-commit install
          poetry run pre-commit install --hook-type commit-msg
          git submodule update --init
          poetry run invoke build
          poetry run invoke fmt
          poetry run invoke lint
          poetry run invoke test
          # poetry run invoke bench
          poetry run invoke doc
          poetry run pip install wheel
          poetry run invoke build --sdist --wheel
